import { defineConfig } from 'tsdown'

export default defineConfig({
  entry: {
    'index': 'src/index.ts',
    'nuxt/module': 'src/nuxt/module.ts',
    'nitro/plugin': 'src/nitro/plugin.ts',
    'nitro/errorHandler': 'src/nitro/errorHandler.ts',
    'runtime/client/log': 'src/runtime/client/log.ts',
    'runtime/client/plugin': 'src/runtime/client/plugin.ts',
    'runtime/server/useLogger': 'src/runtime/server/useLogger.ts',
    'runtime/server/routes/_evlog/ingest.post': 'src/runtime/server/routes/_evlog/ingest.post.ts',
    'runtime/utils/parseError': 'src/runtime/utils/parseError.ts',
    'error': 'src/error.ts',
    'logger': 'src/logger.ts',
    'utils': 'src/utils.ts',
    'types': 'src/types.ts',
    'workers': 'src/workers/index.ts',
    'adapters/axiom': 'src/adapters/axiom.ts',
    'adapters/otlp': 'src/adapters/otlp.ts',
    'adapters/posthog': 'src/adapters/posthog.ts',
    'adapters/sentry': 'src/adapters/sentry.ts',
    'adapters/better-stack': 'src/adapters/better-stack.ts',
    'enrichers': 'src/enrichers/index.ts',
    'pipeline': 'src/pipeline.ts',
    'browser': 'src/browser.ts',
  },
  format: 'esm',
  dts: true,
  clean: true,
  fixedExtension: true,
  external: [
    '#app',
    '#imports',
    'vue',
    'nuxt',
    '@nuxt/kit',
    '@nuxt/schema',
    'nitropack',
    'nitropack/runtime',
    'ofetch',
    'h3',
  ],
})
